export const ID_MONTHS: Record<string, number> = {
  JANUARI: 1,
  FEBRUARI: 2,
  MARET: 3,
  APRIL: 4,
  MEI: 5,
  JUNI: 6,
  JULI: 7,
  AGUSTUS: 8,
  SEPTEMBER: 9,
  OKTOBER: 10,
  NOVEMBER: 11,
  DESEMBER: 12,
};

export const NOISE_LINE_PATTERNS: RegExp[] = [
  /^TANGGAL\s+KETERANGAN\s+CBG\s+MUTASI\s+SALDO$/i,
  /^NO\.?\s*REKENING\s*:/i,
  /^CATATAN:/i,
  /^C A T A T A N/i,
  /^A p a b i l a/i,
  /^R e k e n i n g/i,
  /^•\s*Apabila nasabah/i,
  /^•\s*B C A/i,
  /^•\s*BCA berhak/i,
  /^•\s*$/,
  /^Bersambung ke [Hh]alaman/i,
  /^--\s*\d+\s+of\s+\d+\s*--$/i,
  /^\d+\s*\/\s*\d+$/,
  /^HALAMAN\s*:/i,
  /^PERIODE\s*:/i,
  /^MATA UANG\s*:/i,
  /^INDONESIA$/i,
  /^REKENING (GIRO|TAHAPAN)/i,
  /^MUTASI REKENING/i,
  /^SALDO AWAL\s*:/i,
  /^MUTASI CR\s*:/i,
  /^MUTASI DB\s*:/i,
  /^SALDO AKHIR\s*:/i,
  /^K C P\s/i,
  /^[A-Z](?:\s[A-Z]){8,}$/,
];

export const CHANNEL_RULES: { pattern: RegExp; channel: string }[] = [
  { pattern: /\bBI-?FAST\b/i, channel: "BI-FAST" },
  { pattern: /\bBYR VIA E-BANKING\b/i, channel: "Bayar via E-Banking" },
  { pattern: /\bTRSF E-BANKING\b/i, channel: "TRSF E-Banking" },
  { pattern: /\bSWITCHING CR\b/i, channel: "Switching CR" },
  { pattern: /\bSWITCHING DB\b/i, channel: "Switching DB" },
  { pattern: /\bSETORAN TUNAI\b/i, channel: "Setoran Tunai" },
  { pattern: /\bSETORAN VIA CDM\b/i, channel: "Setoran CDM" },
  { pattern: /\bTARIKAN TUNAI\b/i, channel: "Tarikan Tunai" },
  { pattern: /\bTARIKAN ATM\b/i, channel: "Tarikan ATM" },
  { pattern: /\bTARIKAN PEMINDAH\b/i, channel: "Tarikan Pemindahbukuan" },
  { pattern: /\bKR OTOMATIS\b/i, channel: "KR Otomatis" },
  { pattern: /\bDB OTOMATIS\b/i, channel: "DB Otomatis" },
  { pattern: /\bBIAYA ADM\b/i, channel: "Biaya Admin" },
  { pattern: /\bPAJAK BUNGA\b/i, channel: "Pajak Bunga" },
  { pattern: /\bBUNGA\b/i, channel: "Bunga" },
  { pattern: /\bKARTU KREDIT\b/i, channel: "Kartu Kredit" },
];
